name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install PyBuilder
        run: |
          pip install pybuilder
          pyb verify

      - name: Install pytest & coverage
        run: |
          pip install pytest
          pip install coverage

      - name: Run pytest unit tests
        run: pytest

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Docker image
        run: docker build -t stereyno/assignment-deployment:V1.1 .

      - name: Authenticate to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u stereyno --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push stereyno/assignment-deployment:V1.1

      - name: Run Docker container
        run: docker run stereyno/assignment-deployment:V1.1 python /app/src/main/python/calc.py
