name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install PyBuilder
        run: |
          pip install pybuilder
          pyb

      - name: Run PyBuilder
        run: pyb verify

      - name: Build Docker image
        run: docker build -t assignment-deployment:V1.0 .

      - name: Authenticate to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u stereyno --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push stereyno/assignment-deployment:V1.0